export const ROSCO = [
  { letter: "A", clue: "Disciplina deportiva que hace actualmente Jessi", answer: "Acropilates" },
  { letter: "B", clue: "Banda californiana que vimos en el Lollapalooza", answer: "Blink 182" },
  { letter: "C", clue: "Disciplina artística que hace actualmente Jessi", answer: "Cerámica" },
  { letter: "D", clue: "Contiene D. Título universitario de Joaqui", answer: "Contadora" },
  { letter: "E", clue: "Contiene E. Barrio en el que vive Lucía", answer: "Banfield" },
  { letter: "F", clue: "Colegio al que iban las del oeste menos Lucha", answer: "Franciscano" },
  { letter: "G", clue: "Película favorita de Jessi", answer: "Armageddon" },
  { letter: "H", clue: "Artista de la que Ton compró un disco autografiado recientemente", answer: "Heidi Montag" },
  { letter: "I", clue: "Contiene I. La revista de Lucía era La Primera", answer: "Piedra" },
  { letter: "J", clue: "Curso que está haciendo Joaqui", answer: "Joyería" },
  { letter: "K", clue: "Famoso boliche de zona norte ahora derrumbado", answer: "Ku" },
  { letter: "L", clue: "Contiene L. Apellido de famosa periodista que es el apodo de Lucía", answer: "Santillán" },
  { letter: "M", clue: "Ciudad balnearia argentina favorita de este grupo", answer: "Mar del Plata" },
  { letter: "N", clue: "Profesión que se le asigna erróneamente a Maru", answer: "Nutricionista" },
  { letter: "O", clue: "Banda para la que sacaron las entradas con año y medio de anticipación", answer: "Oasis" },
  { letter: "P", clue: "Nombre de mascota de Ire que se puede comer en un cine", answer: "Pochoclo" },
  { letter: "Q", clue: "Producto de la fábrica de los sueños de Maru", answer: "Queso" },
  { letter: "R", clue: "Ciudad que visitará gran parte del grupo en diciembre", answer: "Rio de Janeiro" },
  { letter: "S", clue: "Contiene S. Profesión de Ire", answer: "Psicóloga" },
  { letter: "T", clue: "Contiene T. Apodo del chongo de Jessi que era vegano", answer: "Plantita" },
  { letter: "U", clue: "Contiene U. Carrera de diseño que estudió Flor.", answer: "Indumentaria" },
  { letter: "V", clue: "Contiene V. Barrio que agrupa a la mayor cantidad de miembros de este grupo", answer: "Saavedra" },
  { letter: "W", clue: "Nombre de pila del papá de Jessi", answer: "Walter" },
  { letter: "X", clue: "Contiene X. País recientemente visitado por Ire", answer: "México" },
  { letter: "Y", clue: "Contiene Y. Famosa artista pop de la que Ton tiene un cuadro en el living.", answer: "Britney" },
  { letter: "Z", clue: "Banda que podría estar en el Spotify de Gime y Jessi “El...”", answer: "Zar" }
];
